import React, { useState, useRef, useEffect } from 'react';

const OptimizedImage = ({ 
  src, 
  alt, 
  className = '', 
  width, 
  height, 
  lazy = true, 
  responsive = false,
  sizes = '100vw',
  quality = 'high',
  ...props 
}) => {
  const [isLoaded, setIsLoaded] = useState(false);
  const [isInView, setIsInView] = useState(!lazy);
  const [hasError, setHasError] = useState(false);
  const imgRef = useRef(null);

  // Intersection Observer for lazy loading
  useEffect(() => {
    if (!lazy || isInView) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsInView(true);
          observer.disconnect();
        }
      },
      { threshold: 0.1, rootMargin: '50px' }
    );

    if (imgRef.current) {
      observer.observe(imgRef.current);
    }

    return () => observer.disconnect();
  }, [lazy, isInView]);

  // Generate different format sources
  const generateSources = (originalSrc) => {
    const baseName = originalSrc.split('.').slice(0, -1).join('.');
    
    // For production, these would be generated by your build process
    return {
      avif: `${baseName}.avif`,
      webp: `${baseName}.webp`,
      original: originalSrc
    };
  };

  // Generate responsive sizes if needed
  const generateResponsiveSources = (originalSrc) => {
    if (!responsive) return { original: originalSrc };
    
    const baseName = originalSrc.split('.').slice(0, -1).join('.');
    const extension = originalSrc.split('.').pop();
    
    return {
      small: `${baseName}-480w.${extension}`,
      medium: `${baseName}-768w.${extension}`,
      large: `${baseName}-1200w.${extension}`,
      original: originalSrc
    };
  };

  const sources = generateSources(src);
  const responsiveSources = generateResponsiveSources(src);

  const handleLoad = () => {
    setIsLoaded(true);
  };

  const handleError = () => {
    setHasError(true);
    setIsLoaded(true);
  };

  // Placeholder component
  const Placeholder = () => (
    <div 
      className={`bg-gray-200 animate-pulse flex items-center justify-center ${className}`}
      style={{ width, height }}
    >
      <svg 
        className="w-12 h-12 text-gray-400" 
        fill="currentColor" 
        viewBox="0 0 20 20"
      >
        <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
      </svg>
    </div>
  );

  // Error fallback
  if (hasError) {
    return <Placeholder />;
  }

  return (
    <div ref={imgRef} className="relative">
      {!isLoaded && <Placeholder />}
      
      {isInView && (
        <picture>
          {/* Modern formats */}
          <source srcSet={sources.avif} type="image/avif" />
          <source srcSet={sources.webp} type="image/webp" />
          
          {/* Responsive images */}
          {responsive && (
            <>
              <source 
                media="(max-width: 480px)" 
                srcSet={responsiveSources.small} 
              />
              <source 
                media="(max-width: 768px)" 
                srcSet={responsiveSources.medium} 
              />
              <source 
                media="(max-width: 1200px)" 
                srcSet={responsiveSources.large} 
              />
            </>
          )}
          
          {/* Fallback */}
          <img
            src={src}
            alt={alt}
            className={`${className} ${isLoaded ? 'opacity-100' : 'opacity-0'} transition-opacity duration-300`}
            width={width}
            height={height}
            sizes={responsive ? sizes : undefined}
            onLoad={handleLoad}
            onError={handleError}
            loading={lazy ? 'lazy' : 'eager'}
            decoding="async"
            {...props}
          />
        </picture>
      )}
    </div>
  );
};

export default OptimizedImage; 